concurrency:
  cancel-in-progress: true
  group: herta-build

on:
  push:
    tags: v*
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          # Windows
          - i686-pc-windows-gnu
          - x86_64-pc-windows-gnu
          # Linux
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu


    steps:
      - uses: actions/checkout@v2

      - name: Install x86 Build Dependencies
        if: startsWith(${{ matrix.target }}, 'i386')
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install build-essential

      - name: Install x86_64 Build Dependencies
        if: startsWith(${{ matrix.target }}, 'x86_64')
        run: sudo apt-get update && sudo apt-get install build-essential

      - uses: actions-rs/toolchain@v1
        name: Setup rust
        with:
          target: ${{ matrix.target }}
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        name: Build release (${{ matrix.target }})
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Prepare artifacts (linux)
        shell: true
        run: |
          BIN_TARGET=$(echo ${{ matrix.target }} | cut -d/ -f 3 | cut -d- -f 1)
          cp target/${{ matrix.target }}/release/argent argent.$BIN_TARGET
        if: contains(matrix.target, 'linux')

      - name: Prepare artifacts (windows)
        shell: true
        run: |
          BIN_TARGET=$(echo ${{ matrix.target }} | cut -d/ -f 3 | cut -d- -f 1)
          cp target/${{ matrix.target }}/release/argent.exe argent-$BIN_TARGET.exe
        if: contains(matrix.target, 'windows')

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: argent*