name: Build Argent Artifacts
on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - i686-pc-windows-gnu
          - armv7-unknown-linux-musleabihf

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build Arifact
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
          use-cross: true

      - name: Get architecture
        id: arch
        env:
          TARGET: ${{ matrix.target }}
        run: echo "::set-output name=target::${TARGET%%-*}"

      - name: Upload Build Artifacts (Linux)
        if: ${{ contains(matrix.target, 'linux') }}
        uses: actions/upload-artifact@v4
        with:
          name: argent.${{ steps.arch.outputs.target }}
          path: target/*/release/argent

      - name: Upload Build Artifacts (Windows)
        if: ${{ contains(matrix.target, 'windows') }}
        uses: actions/upload-artifact@v4
        with:
          name: argent-${{ steps.arch.outputs.target }}.exe
          path: target/*/release/argent.exe
